#!/usr/bin/env bash

# Run this script after having installed LibGDX.

DIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
LIBGDX_DIR="$DIR/.libgdx"
APP="ladybird"
PACKAGE="net.spirangle.$APP"
MAIN_CLASS="Main"
ANDROID_SDK_VERSION=23

DESKTOP_DISPLAY_NAME="Lenovo A820"
DESKTOP_DISPLAY_WIDTH=960
DESKTOP_DISPLAY_HEIGHT=540

DESKTOP_LAUNCHER="\
package net.spirangle.$APP.desktop;\n\
\n\
import com.badlogic.gdx.backends.lwjgl.LwjglApplication;\n\
import com.badlogic.gdx.backends.lwjgl.LwjglApplicationConfiguration;\n\
import net.spirangle.$APP.$MAIN_CLASS;\n\
\n\
public class DesktopLauncher {\n\
\tpublic static void main (String[] arg) {\n\
\t\tLwjglApplicationConfiguration config = new LwjglApplicationConfiguration();\n\
\n\
\t\t/* $DESKTOP_DISPLAY_NAME: */\n\
\t\tconfig.width = $DESKTOP_DISPLAY_WIDTH;\n\
\t\tconfig.height = $DESKTOP_DISPLAY_HEIGHT;\n\
\n\
\t\tnew LwjglApplication(new $MAIN_CLASS(), config);\n\
\t}\n\
}\n\n"

ANDROID_MANIFEST="\
<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"\n\
          package=\"$PACKAGE\"\n\
          android:versionCode=\"1\"\n\
          android:versionName=\"1.0\" >\n\
\n\
\t<uses-sdk android:minSdkVersion=\"8\"\n\
\t          android:targetSdkVersion=\"$ANDROID_SDK_VERSION\" />\n\
\t<uses-permission android:name=\"android.permission.INTERNET\" />
\n\
\t<application android:allowBackup=\"true\"\n\
\t             android:icon=\"@drawable/ic_launcher\"\n\
\t             android:label=\"@string/app_name\"\n\
\t             android:theme=\"@style/GdxTheme\" >\n\
\t\t<activity android:name=\"$PACKAGE.AndroidLauncher\"\n\
\t\t          android:label=\"@string/app_name\"\n\
\t\t          android:screenOrientation=\"sensorLandscape\"\n\
\t\t          android:configChanges=\"keyboard|keyboardHidden|orientation|screenSize\">\n\
\t\t\t<intent-filter>\n\
\t\t\t\t<action android:name=\"android.intent.action.MAIN\" />\n\
\t\t\t\t<category android:name=\"android.intent.category.LAUNCHER\" />\n\
\t\t\t</intent-filter>\n\
\t\t</activity>\n\
\t</application>\n\
\n\
</manifest>\n\n"


rm -rf $LIBGDX_DIR/core/src/net/spirangle
ln -s $DIR/src $LIBGDX_DIR/core/src/net/spirangle

rm -rf $LIBGDX_DIR/android/assets
ln -s $DIR/assets $LIBGDX_DIR/android/assets

echo -e "$DESKTOP_LAUNCHER" > $LIBGDX_DIR/desktop/src/net/spirangle/$APP/desktop/DesktopLauncher.java

echo -e "$ANDROID_MANIFEST" > $LIBGDX_DIR/android/AndroidManifest.xml
